//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UATService.ServiceESB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceESB.ESBSoap")]
    public interface ESBSoap {
        
        // CODEGEN: Generating message contract since element name requestXML from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Request", ReplyAction="*")]
        UATService.ServiceESB.RequestResponse Request(UATService.ServiceESB.RequestRequest request);
        
        // CODEGEN: Generating message contract since element name requestXML from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CommRequest", ReplyAction="*")]
        UATService.ServiceESB.CommRequestResponse CommRequest(UATService.ServiceESB.CommRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Request", Namespace="http://tempuri.org/", Order=0)]
        public UATService.ServiceESB.RequestRequestBody Body;
        
        public RequestRequest() {
        }
        
        public RequestRequest(UATService.ServiceESB.RequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXML;
        
        public RequestRequestBody() {
        }
        
        public RequestRequestBody(string requestXML) {
            this.requestXML = requestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public UATService.ServiceESB.RequestResponseBody Body;
        
        public RequestResponse() {
        }
        
        public RequestResponse(UATService.ServiceESB.RequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestResult;
        
        public RequestResponseBody() {
        }
        
        public RequestResponseBody(string RequestResult) {
            this.RequestResult = RequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CommRequest", Namespace="http://tempuri.org/", Order=0)]
        public UATService.ServiceESB.CommRequestRequestBody Body;
        
        public CommRequestRequest() {
        }
        
        public CommRequestRequest(UATService.ServiceESB.CommRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CommRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXML;
        
        public CommRequestRequestBody() {
        }
        
        public CommRequestRequestBody(string requestXML) {
            this.requestXML = requestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CommRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public UATService.ServiceESB.CommRequestResponseBody Body;
        
        public CommRequestResponse() {
        }
        
        public CommRequestResponse(UATService.ServiceESB.CommRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CommRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CommRequestResult;
        
        public CommRequestResponseBody() {
        }
        
        public CommRequestResponseBody(string CommRequestResult) {
            this.CommRequestResult = CommRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ESBSoapChannel : UATService.ServiceESB.ESBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ESBSoapClient : System.ServiceModel.ClientBase<UATService.ServiceESB.ESBSoap>, UATService.ServiceESB.ESBSoap {
        
        public ESBSoapClient() {
        }
        
        public ESBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ESBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UATService.ServiceESB.RequestResponse UATService.ServiceESB.ESBSoap.Request(UATService.ServiceESB.RequestRequest request) {
            return base.Channel.Request(request);
        }
        
        public string Request(string requestXML) {
            UATService.ServiceESB.RequestRequest inValue = new UATService.ServiceESB.RequestRequest();
            inValue.Body = new UATService.ServiceESB.RequestRequestBody();
            inValue.Body.requestXML = requestXML;
            UATService.ServiceESB.RequestResponse retVal = ((UATService.ServiceESB.ESBSoap)(this)).Request(inValue);
            return retVal.Body.RequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UATService.ServiceESB.CommRequestResponse UATService.ServiceESB.ESBSoap.CommRequest(UATService.ServiceESB.CommRequestRequest request) {
            return base.Channel.CommRequest(request);
        }
        
        public string CommRequest(string requestXML) {
            UATService.ServiceESB.CommRequestRequest inValue = new UATService.ServiceESB.CommRequestRequest();
            inValue.Body = new UATService.ServiceESB.CommRequestRequestBody();
            inValue.Body.requestXML = requestXML;
            UATService.ServiceESB.CommRequestResponse retVal = ((UATService.ServiceESB.ESBSoap)(this)).CommRequest(inValue);
            return retVal.Body.CommRequestResult;
        }
    }
}
