//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UATService.CLoggingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CLoggingService.MonitorSoap")]
    public interface MonitorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LongSecondToLocalTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime LongSecondToLocalTime(long seconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LocalTimeToLongSecond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long LocalTimeToLongSecond(int year, int month, int day, int hour, int minute, int second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UATService.CLoggingService.JobMsgEntity Request(UATService.CLoggingService.JobMsgEntity jme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetClientVersion();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class JobMsgEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jobClassFullNameField;
        
        private string actionField;
        
        private string paramField;
        
        private string hostIPField;
        
        private JobStatus jobStatusField;
        
        private JobResult jobResultField;
        
        private System.DateTime lastEndTimeField;
        
        private string jobInfoField;
        
        private bool needParallelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string JobClassFullName {
            get {
                return this.jobClassFullNameField;
            }
            set {
                this.jobClassFullNameField = value;
                this.RaisePropertyChanged("JobClassFullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Param {
            get {
                return this.paramField;
            }
            set {
                this.paramField = value;
                this.RaisePropertyChanged("Param");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string HostIP {
            get {
                return this.hostIPField;
            }
            set {
                this.hostIPField = value;
                this.RaisePropertyChanged("HostIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public JobStatus JobStatus {
            get {
                return this.jobStatusField;
            }
            set {
                this.jobStatusField = value;
                this.RaisePropertyChanged("JobStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public JobResult JobResult {
            get {
                return this.jobResultField;
            }
            set {
                this.jobResultField = value;
                this.RaisePropertyChanged("JobResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime LastEndTime {
            get {
                return this.lastEndTimeField;
            }
            set {
                this.lastEndTimeField = value;
                this.RaisePropertyChanged("LastEndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string JobInfo {
            get {
                return this.jobInfoField;
            }
            set {
                this.jobInfoField = value;
                this.RaisePropertyChanged("JobInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool NeedParallel {
            get {
                return this.needParallelField;
            }
            set {
                this.needParallelField = value;
                this.RaisePropertyChanged("NeedParallel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum JobStatus {
        
        /// <remarks/>
        Stop,
        
        /// <remarks/>
        Running,
        
        /// <remarks/>
        Stopping,
        
        /// <remarks/>
        Stoped,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum JobResult {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Fail,
        
        /// <remarks/>
        Exception,
        
        /// <remarks/>
        Abort,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MonitorSoapChannel : UATService.CLoggingService.MonitorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorSoapClient : System.ServiceModel.ClientBase<UATService.CLoggingService.MonitorSoap>, UATService.CLoggingService.MonitorSoap {
        
        public MonitorSoapClient() {
        }
        
        public MonitorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime LongSecondToLocalTime(long seconds) {
            return base.Channel.LongSecondToLocalTime(seconds);
        }
        
        public long LocalTimeToLongSecond(int year, int month, int day, int hour, int minute, int second) {
            return base.Channel.LocalTimeToLongSecond(year, month, day, hour, minute, second);
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public UATService.CLoggingService.JobMsgEntity Request(UATService.CLoggingService.JobMsgEntity jme) {
            return base.Channel.Request(jme);
        }
        
        public string GetClientVersion() {
            return base.Channel.GetClientVersion();
        }
    }
}
